# fly.toml app configuration file generated for walletxchange on 2025-01-22T20:13:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'walletxchange'
primary_region = 'otp'

[build]
  image = "nikolahadzhiev/walletxchange:latest"

[env]
  PORT = "8080"
  NODE_ENV="production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
